import os
import json
import re
from typing import List, Optional, Any
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from elasticsearch import AsyncElasticsearch
from langgraph.graph import StateGraph, END

# Import your separated prompts
from prompts import get_guardrail_prompt, get_summarizer_prompt, get_text_to_sql_prompt, get_insights_prompt

# ==========================================
# 1. State Definition (The Shared Memory)
# ==========================================
class BIAgentState(BaseModel):
    session_id: str
    current_tab: str          
    user_query: str
    turn_count: int = 0
    chat_history: List[dict] = Field(default_factory=list)
    context_summary: str = ""      
    guardrail_status: str = ""     
    schemas: str = ""              
    
    # Fields generated by Text-to-SQL Agent
    data_type: Optional[str] = None
    chart_type: Optional[str] = None
    db_selected: Optional[str] = None
    generated_query: Optional[Any] = None
    message_to_user: Optional[str] = None
    sql_retries: int = 0  # To prevent infinite error loops
    
    # Downstream execution fields
    error_log: List[str] = Field(default_factory=list)
    raw_db_response: Optional[Any] = None
    final_ui_payload: Optional[dict] = None

# ==========================================
# 2. LLM & DB Initializations
# ==========================================
VLLM_4B_URL = os.getenv("VLLM_4B_URL", "http://localhost:8000/v1")
VLLM_7B_URL = os.getenv("VLLM_7B_URL", "http://localhost:8001/v1")

# Meta Database Credentials (Used ONLY to fetch schemas & target credentials)
META_ES_HOST = os.getenv("META_ES_HOST", "search-recommendation-engine-ic-new-ltjbsbfr3rs6duuoxwvbckkhee.ap-south-1.es.amazonaws.com")
META_ES_PORT = int(os.getenv("META_ES_PORT", 443))
META_ES_USER = os.getenv("META_ES_USER", "admin")
META_ES_PASS = os.getenv("META_ES_PASS", "CBD_EHc^jY%naw4y")

# 4B Model (Guardrail, Summarizer, Insights)
router_llm = ChatOpenAI(
    base_url=VLLM_4B_URL, api_key="EMPTY", model="Qwen/Qwen3-4B-AWQ", temperature=0.0, max_tokens=150 
)

# 7B Model (Text-to-SQL / Coder Agent)
coder_llm = ChatOpenAI(
    base_url=VLLM_7B_URL, api_key="EMPTY", model="Qwen/Qwen2.5-Coder-7B-Instruct-AWQ", temperature=0.1, max_tokens=800
)

# Async AWS Elasticsearch Client for fetching schemas ONLY
meta_es_client = AsyncElasticsearch(
    hosts=[{"host": META_ES_HOST, "port": META_ES_PORT, "scheme": "https"}],
    basic_auth=(META_ES_USER, META_ES_PASS)
)

# ==========================================
# 3. Node 1: Guardrail Agent
# ==========================================
async def guardrail_node(state: BIAgentState) -> dict:
    print("🛡️ Guardrail Node Triggered")
    system_prompt = get_guardrail_prompt(state.current_tab)
    messages = [SystemMessage(content=system_prompt), HumanMessage(content=state.user_query)]
    
    # Using specific max_tokens for this ultra-fast node
    response = await router_llm.ainvoke(messages)
    clean_result = re.sub(r'<think>.*?</think>', '', response.content, flags=re.DOTALL).strip().upper()
    
    if clean_result not in ["PASS", "FAIL"]:
        clean_result = "PASS" if "PASS" in clean_result else "FAIL"
            
    return {"guardrail_status": clean_result}

# ==========================================
# 4. Node 1.5: Context Builder & Summarizer
# ==========================================
async def context_builder_node(state: BIAgentState) -> dict:
    print("📚 Context Builder Node Triggered")
    turn_count = state.turn_count
    chat_history = state.chat_history
    context_summary = state.context_summary
    
    # 1. Summarization Trigger (Evaluates before adding the current turn)
    if turn_count >= 5 and len(chat_history) > 0:
        history_text = "\n".join([f"{msg['role']}: {msg['content']}" for msg in chat_history])
        summary_prompt = get_summarizer_prompt(context_summary, history_text)
        
        response = await router_llm.ainvoke([HumanMessage(content=summary_prompt)])
        context_summary = re.sub(r'<think>.*?</think>', '', response.content, flags=re.DOTALL).strip()
        
        turn_count = 0 
        chat_history = [] 

    # 2. Schema Retrieval using Meta DB Client
    es_query = {"query": {"term": {"selected_topic.keyword": state.current_tab}}}
    schemas_string = ""
    try:
        es_response = await meta_es_client.search(index="db_schemas", body=es_query)
        hits = es_response.get("hits", {}).get("hits", [])
        
        schema_list = [json.dumps(hit["_source"]) for hit in hits]
        schemas_string = "\n---\n".join(schema_list)
    except Exception as e:
        schemas_string = f"Error: Could not retrieve schema. {e}"

    return {
        "turn_count": turn_count,
        "chat_history": chat_history,
        "context_summary": context_summary,
        "schemas": schemas_string
    }

# ==========================================
# 5. Node 2: Text-to-SQL / Query Router Agent
# ==========================================
async def text_to_sql_node(state: BIAgentState) -> dict:
    print(f"🧠 Text-to-SQL Node Triggered (Attempt {state.sql_retries + 1})")
    error_context = ""
    if state.error_log and len(state.error_log) > 0:
        error_context = f"\n\n[WARNING: Your previous query failed with this error: {state.error_log[-1]}. Please fix the syntax.]"

    augmented_query = state.user_query
    if state.context_summary:
        augmented_query = f"[Previous Conversation Context: {state.context_summary}]\n\nCurrent User Query: {state.user_query}"
        
    augmented_query += error_context

    system_prompt = get_text_to_sql_prompt(state.current_tab, state.schemas)
    messages = [SystemMessage(content=system_prompt), HumanMessage(content=augmented_query)]
    
    response = await coder_llm.ainvoke(messages)
    clean_result = re.sub(r'<think>.*?</think>', '', response.content, flags=re.DOTALL).strip()
    match = re.search(r'\{.*\}', clean_result, re.DOTALL)
    
    if match:
        try:
            parsed_data = json.loads(match.group(0))
            return {
                "data_type": parsed_data.get("data_type"),
                "chart_type": parsed_data.get("chart_type"),
                "db_selected": parsed_data.get("db_selected"),
                "generated_query": parsed_data.get("generated_query"),
                "message_to_user": parsed_data.get("message_to_user")
            }
        except json.JSONDecodeError as e:
            return {"error_log": state.error_log + [f"JSON Parse Error: {str(e)}"], "sql_retries": state.sql_retries + 1}
    else:
        return {"error_log": state.error_log + ["Failed to output a JSON object."], "sql_retries": state.sql_retries + 1}

# ==========================================
# 6. Node 3: Database Execution Agent
# ==========================================
async def execute_db_node(state: BIAgentState) -> dict:
    print("📡 Execute DB Node Triggered")
    # Bypass execution if LLM generated a clarification message or failed query
    if state.data_type == "message" or not state.generated_query or not state.db_selected:
        return {"raw_db_response": None}
        
    query_to_execute = state.generated_query
    
    # --- Resolve Database Type & Dynamic Target Credentials ---
    db_type = "elasticsearch"  # Default fallback
    db_credentials = {}
    try:
        # Re-parse the schemas string to find our db_type and credentials
        for block in state.schemas.split("\n---\n"):
            if not block.strip(): continue
            topic_data = json.loads(block)
            for db in topic_data.get("databases", []):
                if db.get("db_name") == state.db_selected:
                    db_type = db.get("db_type")
                    db_credentials = db.get("db_credentials", {})
                    break
    except Exception as e:
        print(f"⚠️ Could not parse schema for db_type. {e}")

    # ==========================================
    # ROUTE A: ELASTICSEARCH EXECUTION
    # ==========================================
    if db_type == "elasticsearch":
        # 🚨 FAIL-SAFE CAPPING: Force maximum 300 records for table data in ES
        if state.data_type == "table" and isinstance(query_to_execute, dict):
            current_size = query_to_execute.get("size", 300)
            try:
                query_to_execute["size"] = min(int(current_size), 300)
            except (ValueError, TypeError):
                query_to_execute["size"] = 300
                
        try:
            # Initialize dynamic client using credentials fetched via topic_selected
            target_es_client = AsyncElasticsearch(
                hosts=[{
                    "host": db_credentials.get("host"), 
                    "port": db_credentials.get("port", 443), 
                    "scheme": db_credentials.get("scheme", "https")
                }],
                basic_auth=(db_credentials.get("user"), db_credentials.get("pass"))
            )
            
            response = await target_es_client.search(index=state.db_selected, body=query_to_execute)
            await target_es_client.close()  # Clean up ephemeral connection
            
            print("✅ Elasticsearch execution successful!")
            return {
                "raw_db_response": response.raw if hasattr(response, 'raw') else response, 
                "error_log": [],
                "generated_query": query_to_execute
            }
        except Exception as e:
            print(f"❌ ES execution failed: {e}")
            return {"error_log": state.error_log + [str(e)], "raw_db_response": None, "sql_retries": state.sql_retries + 1}
            
    # ==========================================
    # ROUTE B: APACHE PARQUET / SQL EXECUTION
    # ==========================================
    elif db_type == "apache_parquet":
        import duckdb
        print(f"📡 Executing SQL query against Apache Parquet via DuckDB")
        
        # 🚨 FAIL-SAFE CAPPING: Force maximum 300 records for table data in SQL
        if state.data_type == "table" and isinstance(query_to_execute, str):
            if "LIMIT" not in query_to_execute.upper():
                query_to_execute += " LIMIT 300"
                
        try:
            # Use in-memory DuckDB instance to avoid heavy Pandas dataframes
            conn = duckdb.connect(':memory:')
            
            # Register the Parquet file dynamically matching the db_credentials
            if "filepath" in db_credentials:
                filepath = db_credentials["filepath"]
                conn.execute(f"CREATE VIEW {state.db_selected} AS SELECT * FROM read_parquet('{filepath}')")
            
            # Execute the LLM generated SQL
            result = conn.execute(query_to_execute)
            
            # Extract columns and rows into a list of dictionaries (Avoids Pandas Memory Leaks)
            columns = [desc[0] for desc in result.description]
            records = [dict(zip(columns, row)) for row in result.fetchall()]
            
            print("✅ Parquet/SQL execution successful!")
            return {
                "raw_db_response": {"sql_data": records},
                "error_log": [],
                "generated_query": query_to_execute
            }
        except Exception as e:
            print(f"❌ SQL execution failed: {e}")
            return {"error_log": state.error_log + [str(e)], "raw_db_response": None, "sql_retries": state.sql_retries + 1}

# ==========================================
# 7. Node 4: Backend Router & Format Node
# ==========================================
async def format_output_node(state: BIAgentState) -> dict:
    print("🛠️ Format Output Node Triggered")
    payload = {"data_type": state.data_type, "chart_type": state.chart_type, "data": None}
    
    updated_history = state.chat_history.copy()
    updated_history.append({"role": "user", "content": state.user_query})
    ai_memory_text = ""
    
    # Check if the user's query failed the Guardrail Check
    if state.guardrail_status == "FAIL":
        fallback_msg = "I am a specialized Data Assistant. I can only help you query, visualize, and analyze data within this application."
        payload["data"] = fallback_msg
        payload["data_type"] = "message"
        ai_memory_text = fallback_msg

    # Check if the text-to-SQL logic returned a clarification message or failed completely
    elif state.data_type == "message" or (len(state.error_log) > 0 and state.sql_retries >= 2):
        fallback_msg = state.message_to_user if state.data_type == "message" else "I encountered an error generating the data. Please try rephrasing."
        payload["data"] = fallback_msg
        payload["data_type"] = "message"
        ai_memory_text = fallback_msg
        
    elif state.raw_db_response:
        res = state.raw_db_response
        ai_memory_text = f"[Generated {state.data_type} visualization for the user]"
        
        if "sql_data" in res:
            records = res["sql_data"]
            
            if state.data_type == "table":
                payload["data"] = records
                
            elif state.data_type == "metric":
                if records and len(records) > 0:
                    payload["data"] = list(records[0].values())[0]
                else:
                    payload["data"] = 0
                    
            elif state.data_type == "chart":
                categories = []
                series_data = []
                if records and len(records) > 0:
                    keys = list(records[0].keys())
                    cat_key = keys[0]
                    val_key = keys[1] if len(keys) > 1 else keys[0]
                    
                    for row in records:
                        categories.append(str(row[cat_key]))
                        series_data.append(row[val_key])
                        
                payload["data"] = {
                    "categories": categories,
                    "series": [{"name": "Data", "data": series_data}]
                }
                
        else:
            hits = res.get("hits", {}).get("hits", [])
            aggs = res.get("aggregations", {})
            
            if state.data_type == "table":
                payload["data"] = [hit["_source"] for hit in hits]
                
    updated_history.append({"role": "assistant", "content": ai_memory_text})
    
    # Turn count is unconditionally incremented here so ALL interactions are tracked
    return {"final_ui_payload": payload, "chat_history": updated_history, "turn_count": state.turn_count + 1}

# ==========================================
# 8. Node 5: Insights Agent (Triggered for Charts only)
# ==========================================
async def insights_node(state: BIAgentState) -> dict:
    print("💡 Insights Agent Triggered")
    payload = state.final_ui_payload
    updated_history = state.chat_history.copy()
    
    if payload and payload.get("data"):
        data_string = json.dumps(payload["data"])
        prompt = get_insights_prompt(state.user_query, data_string)
        
        response = await router_llm.ainvoke([HumanMessage(content=prompt)])
        clean_insight = re.sub(r'<think>.*?</think>', '', response.content, flags=re.DOTALL).strip()
        
        payload["insight"] = clean_insight
        
        if len(updated_history) > 0 and updated_history[-1]["role"] == "assistant":
            updated_history[-1]["content"] += f" Insight provided: {clean_insight}"
        
    return {"final_ui_payload": payload, "chat_history": updated_history}

# ==========================================
# 9. LangGraph Conditional Routing & Compilation
# ==========================================
def route_guardrail(state: BIAgentState) -> str:
    if state.guardrail_status == "FAIL":
        # Route to formatting node so the state persists properly into Redis
        return "format_output"
    return "context_builder"

def route_sql(state: BIAgentState) -> str:
    if len(state.error_log) > 0 and state.sql_retries < 2:
        print(f"🔄 Retrying JSON Generation... (Attempt {state.sql_retries + 1})")
        return "text_to_sql"
    elif state.data_type == "message" or len(state.error_log) > 0:
        return "format_output"
    return "execute_db"

def route_db_error(state: BIAgentState) -> str:
    if len(state.error_log) > 0 and state.sql_retries < 2:
        print(f"🔄 Retrying DB Query Generation... (Attempt {state.sql_retries + 1})")
        return "text_to_sql"
    return "format_output"

def route_insights(state: BIAgentState) -> str:
    if state.data_type == "chart" and not state.error_log:
        return "insights"
    return END

def create_bi_graph(checkpointer=None):
    workflow = StateGraph(BIAgentState)
    
    workflow.add_node("guardrail", guardrail_node)
    workflow.add_node("context_builder", context_builder_node)
    workflow.add_node("text_to_sql", text_to_sql_node)
    workflow.add_node("execute_db", execute_db_node)
    workflow.add_node("format_output", format_output_node)
    workflow.add_node("insights", insights_node)
    
    workflow.set_entry_point("guardrail")
    workflow.add_conditional_edges("guardrail", route_guardrail)
    workflow.add_edge("context_builder", "text_to_sql")
    workflow.add_conditional_edges("text_to_sql", route_sql)
    workflow.add_conditional_edges("execute_db", route_db_error)
    workflow.add_conditional_edges("format_output", route_insights)
    workflow.add_edge("insights", END)
    
    return workflow.compile(checkpointer=checkpointer)