import os
import json
import re
from typing import TypedDict, List, Optional, Any
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from elasticsearch import AsyncElasticsearch
from prompts import get_guardrail_prompt, get_summarizer_prompt

# ==========================================
# 1. State Definition (The Shared Memory)
# ==========================================
class BIAgentState(TypedDict):
    session_id: str
    current_tab: str          # e.g., "sales_dashboard", "support_tickets"
    user_query: str
    turn_count: int
    chat_history: List[dict]  # e.g., [{"role": "user", "content": "..."}, {"role": "ai", "content": "..."}]
    context_summary: str      # Compressed memory of older conversations
    guardrail_status: str     # "PASS" or "FAIL"
    schemas: str              # Stringified DB schemas retrieved from Elasticsearch
    
    # Fields for downstream nodes (Text-to-SQL, Routing, Insights)
    data_type: Optional[str]
    chart_type: Optional[str]
    db_selected: Optional[str]
    generated_query: Optional[Any]
    message_to_user: Optional[str]
    error_log: Optional[List[str]]
    raw_db_response: Optional[Any]
    final_ui_payload: Optional[dict]

# ==========================================
# 2. LLM & DB Initializations
# ==========================================
# Pointing to your Docker vLLM instances (assuming running on localhost/docker network)
VLLM_4B_URL = os.getenv("VLLM_4B_URL", "http://localhost:8000/v1")
VLLM_7B_URL = os.getenv("VLLM_7B_URL", "http://localhost:8001/v1")
ES_URL = os.getenv("ES_URL", "http://localhost:9200")

# 4B Model: Used for Guardrail, Summarization, and Insights
router_llm = ChatOpenAI(
    base_url=VLLM_4B_URL,
    api_key="EMPTY", # vLLM doesn't require a real key
    model="Qwen/Qwen3-4B-AWQ",
    temperature=0.0, # 0.0 for strict, deterministic classification
    max_tokens=10 
)

# Async Elasticsearch Client
es_client = AsyncElasticsearch(hosts=[ES_URL])

# ==========================================
# 3. Node 1: Guardrail Agent
# ==========================================
async def guardrail_node(state: BIAgentState) -> dict:
    """
    A sub-0.5s latency checkpoint. Ensures prompt is data-related.
    """
    user_query = state.get("user_query", "")
    current_tab = state.get("current_tab", "general")
    
    system_prompt = get_guardrail_prompt(current_tab)
    
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_query)
    ]
    
    response = await router_llm.ainvoke(messages)
    raw_result = response.content
    
    # Strip <think> tags generated by reasoning models
    clean_result = re.sub(r'<think>.*?</think>', '', raw_result, flags=re.DOTALL).strip().upper()
    
    # Failsafe fallback
    if clean_result not in ["PASS", "FAIL","pass","fail"]:
        # If it generated extra text, check if PASS is at least in the string
        if "PASS" or "pass" in clean_result:
            clean_result = "PASS"
        else:
            clean_result = "FAIL"
            
    return {"guardrail_status": clean_result}

# ==========================================
# 4. Node 1.5: Context Builder & Summarizer
# ==========================================
async def context_builder_node(state: BIAgentState) -> dict:
    """
    Handles memory compression and fetches schemas from Elasticsearch (NoSQL).
    """
    turn_count = state.get("turn_count", 0) + 1
    chat_history = state.get("chat_history", [])
    context_summary = state.get("context_summary", "")
    current_tab = state.get("current_tab", "")
    
    # --- 1. Summarization Trigger (Every 5 turns) ---
    if turn_count >= 5 and len(chat_history) > 0:
        # Increase max_tokens dynamically for summarization
        summarizer_llm = ChatOpenAI(
            base_url=VLLM_4B_URL, api_key="EMPTY", model="Qwen/Qwen3-4B-AWQ", temperature=0.3, max_tokens=150
        )
        
        history_text = "\n".join([f"{msg['role']}: {msg['content']}" for msg in chat_history])
        summary_prompt = get_summarizer_prompt(context_summary, history_text)
        
        response = await summarizer_llm.ainvoke([HumanMessage(content=summary_prompt)])
        raw_summary = response.content
        
        # Strip <think> tags for the summarizer as well
        context_summary = re.sub(r'<think>.*?</think>', '', raw_summary, flags=re.DOTALL).strip()
        
        # Reset turn count and clear immediate history (Redis will still have the full log if needed)
        turn_count = 0 
        chat_history = [] 

    # --- 2. Schema Retrieval from Elasticsearch ---
    # We query ES based on the user's current_tab
    es_query = {
        "query": {
            "term": {
                "selected_topic.keyword": current_tab
            }
        }
    }
    
    schemas_string = ""
    try:
        # Assuming you have an index called "db_schemas"
        es_response = await es_client.search(index="db_schemas", body=es_query)
        hits = es_response.get("hits", {}).get("hits", [])
        
        schema_list = []
        for hit in hits:
            source = hit["_source"]
            schema_list.append(json.dumps(source))
            
        schemas_string = "\n---\n".join(schema_list)
        
    except Exception as e:
        print(f"Error fetching schemas: {e}")
        schemas_string = "Error: Could not retrieve schema for this topic."

    return {
        "turn_count": turn_count,
        "chat_history": chat_history,
        "context_summary": context_summary,
        "schemas": schemas_string
    }